name: TestCI
on:
  push:
    branches: [ main ]
    paths-ignore:
     - '.gitignore'
     - '.dockerignore'
     - 'README.md'
#    paths:
#      - '**.py'
  pull_request:
    branches: [ main ]

jobs:
  ci:
    runs-on: ubuntu-latest
    outputs:
      IMAGE_TAG: ${{ steps.set-var.outputs.IMAGE_TAG }}
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Set var
      id: set-var
      run: |
        echo ::set-output name=ECR_REGISTRY::${{ steps.login-ecr.outputs.registry }}
        echo ::set-output name=ECR_REPOSITORY::yo-demo
        echo ::set-output name=IMAGE_TAG::$(cat VERSION)

    - name: Docker image Build
      id: build-image
      run: |
        docker build -f Dockerfile -t ${{ steps.set-var.outputs.ECR_REGISTRY }}/${{ steps.set-var.outputs.ECR_REPOSITORY }}:${{ steps.set-var.outputs.IMAGE_TAG }} .

    - name: Docker image Push
      id: push-image
      run: |
        docker push ${{ steps.set-var.outputs.ECR_REGISTRY }}/${{ steps.set-var.outputs.ECR_REPOSITORY }}:${{ steps.set-var.outputs.IMAGE_TAG }}
  cd:
    needs: [ ci ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Target Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          repository: AWS03-CloudSchool/dev-react-chart
          ref: main
          lfs: true
          token: ${{ secrets.CICD }}

      - name: Replace image tag in helm values (LOCAL)
        uses: mikefarah/yq@master
        env:
          IMAGE_TAG: ${{ needs.ci.outputs.IMAGE_TAG }}
        with:
          cmd: yq eval -i '.image.tag = env(IMAGE_TAG)' 'demo/values.yaml'

      - name: Commit helm chart changes
        env:
          IMAGE_TAG: ${{ needs.ci.outputs.IMAGE_TAG }}
        run: |
          cd react-app
          git config --global user.email "rnjsduddh05@gmail.com"
          git config --global user.name "Kwonyoungoh"

          git add values.yaml
          git commit --message "ci: Update demo image tag to $IMAGE_TAG"

      - name: Push commit
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.CICD }}
          repository: AWS03-CloudSchool/dev-react-chart